name: Automated Branch Creation

on:
  issues:
    types: [opened]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Extract issue details
      id: extract_issue
      run: |
        issue_title=$(echo "${{ github.event.issue.title }}" | tr ' ' '-' | tr -dc '[:alnum:]-')
        
        # Determine the issue type based on the label
        issue_type=""
        for label in "${{ github.event.issue.labels[*] }}"; do
          case "$label" in
            "âš™ï¸ Efficiency & Performance")
              issue_type="efficiency"
              ;;
            "âœ¨ Feature Request")
              issue_type="feature"
              ;;
            "ðŸ› Bug Report" | "âš ï¸ Security Vulnerability")
              issue_type="bug"
              ;;
            "ðŸ“ Documentation")
              issue_type="documentation"
              ;;
            "ðŸ¤” Support or Usage Questions")
              issue_type="support"
              ;;
          esac
        done

        # Fallback in case no matching label is found
        if [ -z "$issue_type" ]; then
          issue_type="misc"
        fi

        echo "issue_title=$issue_title" >> $GITHUB_ENV
        echo "issue_type=$issue_type" >> $GITHUB_ENV
        
    - name: Create branch name
      id: branch_name
      run: echo "branch_name=${{ env.issue_type }}/REACT-FRAMIFY-${{ env.issue_title }}" >> $GITHUB_ENV
    
    - name: Create branch
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git checkout -b ${{ env.branch_name }}
        git push origin ${{ env.branch_name }}